vim.keymap.set('i', '<C-j>', '<ESC>', { desc = 'Exit from insert mode' })
vim.keymap.set('n', '<C-j>', '<PageDown>', { desc = 'Page down' })
vim.keymap.set('n', '<C-k>', '<PageUp>', { desc = 'Page up' })
vim.keymap.set({ 'n', 'v', 'i' }, '<C-f>', '<ESC>:NvimTreeToggle<CR>', { desc = 'Toggle Nvim tree' })
vim.keymap.set('n', '<F5>', vim.cmd.UndotreeToggle)
vim.keymap.set('n', '<F4>', vim.cmd.vsplit)
