vim.lsp.config['intelephense'] = {
  -- Command and arguments to start the server.
  -- cmd = { 'lua-language-server' },
  filetypes = { 'php' },
  settings = {

    files = {
      maxSize = 1000000,
    },
    -- Ensure stubs are enabled
    stubs = {
      'bcmath',
      'bz2',
      'calendar',
      'Core',
      'curl',
      'date',
      'dba',
      'dom',
      'enchant',
      'fileinfo',
      'filter',
      'ftp',
      'gd',
      'gettext',
      'hash',
      'iconv',
      'imap',
      'intl',
      'json',
      'ldap',
      'libxml',
      'mbstring',
      'mcrypt',
      'mysql',
      'mysqli',
      'password',
      'pcntl',
      'pcre',
      'PDO',
      'pdo_mysql',
      'Phar',
      'readline',
      'recode',
      'Reflection',
      'regex',
      'session',
      'SimpleXML',
      'soap',
      'sockets',
      'sodium',
      'SPL',
      'standard',
      'superglobals',
      'sysvsem',
      'sysvshm',
      'tokenizer',
      'xml',
      'xdebug',
      'xmlreader',
      'xmlwriter',
      'yaml',
      'zip',
      'zlib',
      'wordpress',
      'phpunit',
      'laravel',
    },
  },
}
vim.lsp.enable 'intelephense'
