vim.keymap.set('i', '<C-j>', '<ESC>', { desc = 'Exit from insert mode' })
vim.keymap.set({ 'n', 'v' }, '<C-j>', '<PageDown>', { desc = 'Page down' })
vim.keymap.set({ 'n', 'v' }, '<C-k>', '<PageUp>', { desc = 'Page up' })
-- vim.keymap.set({ 'n', 'v', 'i' }, '<C-f>', vim.cmd.NvimTreeToggle, { desc = 'Toggle Nvim [F]ile tree' })
-- vim.keymap.set('n', '<leader>u', vim.cmd.UndotreeToggle, { desc = 'Toggle [U]ndo tree' })
vim.keymap.set('n', '<F4>', vim.cmd.vsplit, { desc = 'Split verticaly' })
vim.keymap.set({ 'n', 'v', 'i' }, '<F9>', '<cmd>split<CR><cmd>resize 15<CR><cmd>terminal<CR>i', { desc = '[F9] Open Terminal' })
vim.keymap.set({ 'n', 'v', 'i' }, '<F10>', vim.cmd.close, { desc = '[F10] Close window' })
vim.keymap.set({ 'n', 'v' }, 'dm', '<cmd>delmarks a-zA-Z0-9 | echo "All marks were cleared!"<CR>', { desc = 'Delete all marks' })
vim.keymap.set('n', 'tq', vim.cmd.TodoQuickFix, { desc = 'Open Todos in QuickFix' })
vim.keymap.set('n', '<leader>nd', vim.cmd.NoiceDismiss, { desc = '[D]ismiss Noice Messages' })
vim.keymap.set('n', '<leader>ns', vim.cmd.NoiceAll, { desc = '[S]how Noice Messages' })
vim.keymap.set('n', '<leader>sN', vim.cmd.NoiceSnacks, { desc = '[S]how Noice Snack Messages' })

-- vim.keymap.set({ 'n', 'v', 'i' }, '<leader>cs', '<cmd>split<CR><cmd>resize 15<CR><cmd>terminal<CR>i', { desc = '[C]onsole [S]plit' })
-- vim.keymap.set({ 'n', 'v', 'i' }, '<leader>cv', '<cmd>vsplit<CR><cmd>terminal<CR>i', { desc = '[C]onsole [V]ertical split' })
